### ISSUE TITLE
language option doesn't show on create page

### ISSUE THREAD

**Issue by tankibaj** [ngiraud/nova-translatable-v2#1]
Hi,

The language selection option doesn't appear on the create page. Its only show on the update page.

**Comment by ngiraud** [comment]
Hi,

Which version of Nova do you use? Seems working for me on Nova 2.12, which is the latest stable release for Laravel 6. Normally you can't install this package with Laravel 7.

**Comment by tankibaj** [comment]
I'm using nova v3.3.2 with Laravel 7. Probably that's why not working. Do you have any plan to update the package for Laravel 7 support? Thanks.

**Comment by ngiraud** [comment]
It seems working on the latest Nova update (v3.4.1), so it's fix for me. I will still add an update for the composer dependancies.

**Comment by ngiraud** [comment]
seen on https://nova.laravel.com/releases :
- v3.4.0 : Fixed issue resolving fields with default attributes on create forms.

This is what fixed the bug
